import { Button } from "@/components/ui/button";
import { ArrowRight, Check, CheckCircle2, Home, MapPin, PackageCheck, Route, Search, Truck } from "lucide-react";
import { useState } from "react";

const routeSteps = [
  { title: "Port cleared", detail: "Dar es Salaam · 19 Sep", done: true },
  { title: "Handed to road carrier", detail: "TALISM Express · 20 Sep", done: true },
  { title: "In transit to destination", detail: "Morogoro Road corridor · Today", done: true, live: true },
  { title: "Out for delivery", detail: "Expected 22 Sep · 09:00–13:00", done: false },
  { title: "Delivered", detail: "Doorstep confirmation", done: false },
];

export default function TrackingLand() {
  const [query, setQuery] = useState("TAL-48291");
  const [searched, setSearched] = useState(true);

  return (
    <main className="bg-[#f3f5f1]">
      <section className="bg-[#173c3d] py-16 text-white sm:py-20"><div className="container"><div className="flex flex-col justify-between gap-10 lg:flex-row lg:items-end"><div className="max-w-2xl"><p className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e7a15a]"><span className="h-px w-8 bg-[#73c4bd]" /> 03 / Last-mile control</p><h1 className="mt-6 font-display text-6xl font-bold uppercase leading-[0.86] tracking-[-0.04em] sm:text-8xl">At land<span className="text-[#73c4bd]">.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#c5d5ce]">The last handoff is still part of the journey. Follow your cargo from clearance to the moment it reaches your doorstep.</p></div><div className="w-full max-w-md rounded-[18px] border border-white/10 bg-[#204c4c] p-3"><div className="mb-2 flex items-center gap-2 px-2 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a5c4ba]"><Search size={13} /> Find a shipment</div><div className="flex gap-2"><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-12 min-w-0 flex-1 rounded-xl border border-white/10 bg-[#173c3d] px-4 text-sm text-white outline-none placeholder:text-[#81a59d]" placeholder="Container or tracking ID" /><Button onClick={() => setSearched(true)} className="h-12 rounded-xl bg-[#e7a15a] px-5 font-bold text-[#173c3d] hover:bg-[#f1b675]">Search</Button></div></div></div></div></section>

      <section className="container py-12 sm:py-16">{searched && <div className="mb-8 flex flex-col justify-between gap-4 rounded-2xl border border-[#cbdad2] bg-[#e9f2ed] px-5 py-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-[#c5e9dc] text-[#28745f]"><Route size={17} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#5e8377]">Road movement live</p><p className="mt-1 text-sm font-bold text-[#23473f]">Showing latest status for {query || "TAL-48291"}</p></div></div><span className="text-[11px] font-bold uppercase tracking-[0.14em] text-[#578173]">Driver signal active</span></div>}
        <div className="grid gap-6 lg:grid-cols-[0.9fr_1.1fr]">
          <div className="rounded-[24px] bg-[#102234] p-6 text-white shadow-[0_20px_60px_rgba(14,34,51,0.12)] sm:p-8"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#73c4bd]">Delivery destination</p><h2 className="mt-2 font-display text-3xl font-bold uppercase">Doorstep route</h2></div><span className="flex size-11 items-center justify-center rounded-xl bg-[#e7a15a]/15 text-[#e7a15a]"><Home size={20} /></span></div><div className="relative mt-9 overflow-hidden rounded-2xl border border-white/10 bg-[#173246] p-6"><div className="absolute right-0 top-0 h-32 w-48 bg-[radial-gradient(ellipse_at_center,rgba(115,196,189,0.22),transparent_65%)]" /><div className="relative"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#86a8a1]">Delivering to</p><p className="mt-3 text-lg font-bold">Plot 14, Mbezi Beach</p><p className="mt-1 text-sm text-[#9db5af]">Dar es Salaam, Tanzania</p><div className="my-7 h-px bg-white/10" /><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-[0.13em] text-[#75968f]">Carrier</p><p className="mt-1 font-bold">TALISM Express</p></div><div className="text-right"><p className="text-[10px] uppercase tracking-[0.13em] text-[#75968f]">Vehicle</p><p className="mt-1 font-bold">TZ 458 EPR</p></div></div></div></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#173246] p-4"><p className="text-[10px] uppercase tracking-[0.12em] text-[#75968f]">Current leg</p><p className="mt-2 font-display text-2xl font-bold">62 km</p><p className="mt-1 text-xs text-[#95ada7]">to destination</p></div><div className="rounded-xl bg-[#173246] p-4"><p className="text-[10px] uppercase tracking-[0.12em] text-[#75968f]">ETA</p><p className="mt-2 font-display text-2xl font-bold text-[#e7a15a]">22 Sep</p><p className="mt-1 text-xs text-[#95ada7]">09:00–13:00</p></div></div></div>

          <div className="rounded-[24px] border border-[#d7e0da] bg-white/70 p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#6b8b84]">Last-mile timeline</p><h2 className="mt-2 font-display text-3xl font-bold uppercase text-[#102234]">Almost home</h2></div><span className="flex size-11 items-center justify-center rounded-xl bg-[#e1f2ed] text-[#4f9e8f]"><Truck size={20} /></span></div><div className="mt-9">{routeSteps.map((step, index) => <div key={step.title} className="relative flex gap-4 pb-7 last:pb-0"><div className="relative flex w-5 shrink-0 justify-center">{index < routeSteps.length - 1 && <span className="absolute top-5 h-full w-px bg-[#cfe0d8]" />}{step.done ? <span className={`relative z-10 flex size-5 items-center justify-center rounded-full ${step.live ? "bg-[#e7a15a] text-[#102234] shadow-[0_0_0_5px_rgba(231,161,90,0.16)]" : "bg-[#73c4bd] text-[#102234]"}`}><Check size={12} strokeWidth={3} /></span> : <span className="relative z-10 mt-0.5 size-4 rounded-full border-2 border-[#bfd0c8] bg-white" />}</div><div><div className="flex flex-wrap items-center gap-2"><h3 className={`text-sm font-bold ${step.done ? "text-[#183c39]" : "text-[#70827c]"}`}>{step.title}</h3>{step.live && <span className="rounded-full bg-[#f8e6d2] px-2 py-0.5 text-[9px] font-bold uppercase tracking-[0.1em] text-[#aa6d30]">Now</span>}</div><p className="mt-1 text-xs text-[#778a83]">{step.detail}</p></div></div>)}</div><div className="mt-8 flex items-start gap-3 rounded-xl border border-[#dbe6df] bg-[#f1f6f2] p-4"><PackageCheck size={19} className="mt-0.5 shrink-0 text-[#5b9788]" /><p className="text-xs leading-5 text-[#678078]">We will notify you when the driver is within the final delivery zone. Keep your phone close for the handoff confirmation.</p></div></div>
        </div>
      </section>

      <section className="border-t border-[#dbe2dc] bg-[#e1e9e4] py-10"><div className="container flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><CheckCircle2 size={20} className="text-[#5c8e86]" /><p className="text-sm text-[#5d766e]">Your shipment is <strong className="text-[#183c39]">in motion</strong> and the delivery window is on track.</p></div><a href="mailto:support@talism-gateway.com" className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[0.13em] text-[#183c39]">Contact operations <ArrowRight size={14} /></a></div></section>
    </main>
  );
}
