import { ArrowRight, Box, CheckCircle2, Globe2, MapPin, PackageCheck, Warehouse as WarehouseIcon } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const warehouses = [
  { city: "Dar es Salaam", country: "Tanzania", region: "East Africa", type: "Talism facility", status: "Receiving now", detail: "Port clearance, consolidation, and last-mile dispatch.", accent: "#73c4bd" },
  { city: "Dubai", country: "United Arab Emirates", region: "Middle East", type: "Partner facility", status: "Receiving now", detail: "Air and sea consolidation for Gulf and Asia routes.", accent: "#e7a15a" },
  { city: "Guangzhou", country: "China", region: "Asia", type: "Partner facility", status: "Receiving now", detail: "Supplier receiving, inspection, and export preparation.", accent: "#a8a6dd" },
  { city: "London", country: "United Kingdom", region: "Europe", type: "Partner facility", status: "Receiving now", detail: "Parcel consolidation and international forwarding.", accent: "#84b7a2" },
  { city: "New Jersey", country: "United States", region: "North America", type: "Partner facility", status: "Receiving now", detail: "E-commerce receiving and consolidated ocean freight.", accent: "#73a9c4" },
  { city: "Mumbai", country: "India", region: "South Asia", type: "Partner facility", status: "Coming soon", detail: "Planned sourcing and consolidation point for the region.", accent: "#d08d9b" },
];

export default function Warehouses() {
  const [filter, setFilter] = useState("All locations");
  const regions = ["All locations", ...Array.from(new Set(warehouses.map((warehouse) => warehouse.region)))];
  const visible = filter === "All locations" ? warehouses : warehouses.filter((warehouse) => warehouse.region === filter);

  return (
    <main className="bg-[#f3f5f1]"><section className="bg-[#173c3d] py-16 text-white sm:py-20"><div className="container grid gap-10 lg:grid-cols-[1fr_0.75fr] lg:items-end"><div className="max-w-2xl"><p className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[0.2em] text-[#e7a15a]"><span className="h-px w-8 bg-[#73c4bd]" /> 05 / Network coverage</p><h1 className="mt-6 font-display text-6xl font-bold uppercase leading-[0.86] tracking-[-0.04em] sm:text-8xl">Available<br /><span className="text-[#73c4bd]">warehouses.</span></h1><p className="mt-7 max-w-lg text-base leading-7 text-[#c5d5ce]">Use a Talism-owned or trusted partner warehouse as your receiving point. We keep your cargo moving between origin, consolidation, and delivery.</p></div><div className="rounded-[22px] border border-white/10 bg-[#204c4c] p-6"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-xl bg-[#73c4bd]/15 text-[#73c4bd]"><Globe2 size={21} /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.17em] text-[#a5c4ba]">Network snapshot</p><p className="mt-1 font-display text-3xl font-bold">6 countries</p></div></div><p className="mt-5 text-xs leading-5 text-[#b3cbc2]">More receiving points are being added as the gateway grows.</p></div></div></section>

      <section className="container py-12 sm:py-16"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#6b8b84]">Receiving network</p><h2 className="mt-2 font-display text-4xl font-bold uppercase text-[#102234]">Find your nearest handoff</h2></div><div className="flex flex-wrap gap-2">{regions.map((region) => <button key={region} onClick={() => setFilter(region)} className={`rounded-full px-4 py-2 text-[10px] font-bold uppercase tracking-[0.12em] transition ${filter === region ? "bg-[#0b1a2a] text-white" : "border border-[#d3dfd8] bg-white/60 text-[#688079] hover:bg-white"}`}>{region}</button>)}</div></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{visible.map((warehouse) => <article key={warehouse.city} className="group rounded-[22px] border border-[#d7e0da] bg-white/70 p-6 transition-all duration-300 hover:-translate-y-1 hover:bg-white hover:shadow-[0_18px_50px_rgba(25,50,45,0.08)]"><div className="flex items-start justify-between"><span className="flex size-11 items-center justify-center rounded-xl" style={{ background: `${warehouse.accent}20`, color: warehouse.accent }}><WarehouseIcon size={20} /></span><span className={`rounded-full px-2.5 py-1 text-[9px] font-bold uppercase tracking-[0.12em] ${warehouse.status === "Receiving now" ? "bg-[#e1f2ed] text-[#4f907e]" : "bg-[#f8e6d2] text-[#a56c32]"}`}>{warehouse.status}</span></div><div className="mt-8"><p className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#78908a]">{warehouse.type} · {warehouse.region}</p><h3 className="mt-2 font-display text-3xl font-bold uppercase text-[#183c39]">{warehouse.city}</h3><p className="mt-1 text-sm text-[#71837c]">{warehouse.country}</p><p className="mt-5 min-h-12 text-sm leading-6 text-[#71837c]">{warehouse.detail}</p></div><div className="mt-7 flex items-center justify-between border-t border-[#e1e9e4] pt-4"><span className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.12em] text-[#64857d]"><MapPin size={13} /> Receiving point</span><ArrowRight size={16} className="text-[#7ca399] transition-transform group-hover:translate-x-1" /></div></article>)}</div></section>

      <section className="border-t border-[#dbe2dc] bg-[#e1e9e4] py-14"><div className="container grid gap-6 lg:grid-cols-[1fr_1fr] lg:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#6b8b84]">How it works</p><h2 className="mt-3 font-display text-4xl font-bold uppercase text-[#102234]">A warehouse is your cargo’s first safe handoff.</h2></div><div className="grid gap-4 sm:grid-cols-3">{[{ icon: Box, title: "Receive", text: "Use the warehouse address when ordering." }, { icon: PackageCheck, title: "Consolidate", text: "Combine shipments where it makes sense." }, { icon: CheckCircle2, title: "Dispatch", text: "Track the next leg to your doorstep." }].map((item) => { const Icon = item.icon; return <div key={item.title} className="rounded-2xl bg-white/60 p-5"><Icon size={18} className="text-[#5a8f85]" /><h3 className="mt-6 text-sm font-bold text-[#294b46]">{item.title}</h3><p className="mt-2 text-xs leading-5 text-[#71877f]">{item.text}</p></div>; })}</div></div></section><section className="bg-[#0b1a2a] py-12 text-white"><div className="container flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="font-display text-3xl font-bold uppercase">Ready to source from anywhere?</p><p className="mt-1 text-sm text-[#9eb5af]">Start with a request and we’ll guide the receiving point.</p></div><Link href="/order" className="flex items-center gap-2 rounded-full bg-[#e7a15a] px-5 py-3 text-[11px] font-bold uppercase tracking-[0.14em] text-[#102234]">Order with us <ArrowRight size={14} /></Link></div></section>
    </main>
  );
}
